### ISSUE TITLE
Running example from examples-scala.jar

### ISSUE THREAD

**Issue by jhagege** [streaming-with-flink/examples#1]
Hi,
I'm trying to run the examples from the chapter 1.
`./bin/flink run -c io.github.streamingwithflink.AverageSensorReadings examples-scala.jar`

I downloaded the files from the github repo (the link here does not work: https://streaming-with-flink.github.io/examples/)

Thanks for your help !

**Comment by vasia** [comment]
Thank you for reporting this @jhagege! I have updated the link. Let us know if you have further problems.

**Comment by jhagege** [comment]
Thanks !
